on:
  push:
    branches:
      - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use.
          
      - run: echo "# Test" | pandoc -t html
      
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
          
      - run: conda --version
      - run: which python
      
      - uses: r-lib/actions/setup-r@v2-branch
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.2-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-4.2-3-
          
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown")
          remotes::install_github("ModelOriented/DrWhyTemplate")
          install.packages("textshaping")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
